import { createServerClient } from '@supabase/ssr';
import { NextResponse } from 'next/server';
import type { NextRequest } from 'next/server';

export const dynamic = 'force-dynamic';

const SITE_URL = 'https://www.peopleandyouth.org';

export async function GET(request: NextRequest) {
  const requestUrl = request.nextUrl;

  const tokenHash =
    requestUrl.searchParams.get('token_hash') || '';

  const type =
    requestUrl.searchParams.get('type') || 'magiclink';

  const next =
    requestUrl.searchParams.get('next') ||
    '/admin/command-centre';

  /*
   * ============================================================
   * VALIDATE TOKEN
   * ============================================================
   */

  if (!tokenHash) {
    return NextResponse.redirect(
      `${SITE_URL}/admin/login?error=${encodeURIComponent(
        'Invalid or missing authentication token.'
      )}`
    );
  }

  /*
   * Only the authentication flows generated by
   * /api/auth/send-link are permitted.
   */

  if (!['magiclink', 'recovery'].includes(type)) {
    return NextResponse.redirect(
      `${SITE_URL}/admin/login?error=${encodeURIComponent(
        'Invalid authentication request type.'
      )}`
    );
  }

  /*
   * ============================================================
   * CREATE RESPONSE FIRST
   * ============================================================
   *
   * This is important.
   *
   * Supabase SSR may need to write refreshed authentication
   * cookies while verifyOtp() executes.
   *
   * Those cookies MUST be attached to the same response that
   * ultimately redirects the browser.
   */

  let response = NextResponse.redirect(
    `${SITE_URL}${
      next === '/admin/reset-password' ||
      next === '/admin/command-centre'
        ? next
        : '/admin/command-centre'
    }`
  );

  /*
   * ============================================================
   * SERVER-SIDE SUPABASE SSR CLIENT
   * ============================================================
   */

  const supabase = createServerClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
    {
      cookies: {
        getAll() {
          return request.cookies.getAll();
        },

        setAll(cookiesToSet) {
          /*
           * Keep the request cookie state synchronized.
           */
          cookiesToSet.forEach(
            ({ name, value }) => {
              request.cookies.set(name, value);
            }
          );

          /*
           * Re-create the redirect response so that all Supabase
           * session cookies are written onto the actual response
           * returned to the browser.
           */

          response = NextResponse.redirect(
            `${SITE_URL}${
              next === '/admin/reset-password' ||
              next === '/admin/command-centre'
                ? next
                : '/admin/command-centre'
            }`
          );

          cookiesToSet.forEach(
            ({ name, value, options }) => {
              response.cookies.set(
                name,
                value,
                options
              );
            }
          );
        },
      },
    }
  );

  /*
   * ============================================================
   * VERIFY SUPABASE TOKEN
   * ============================================================
   */

  const { data, error } =
    await supabase.auth.verifyOtp({
      token_hash: tokenHash,
      type: type as 'magiclink' | 'recovery',
    });

  if (error || !data.session) {
    console.error(
      '[AUTH CONFIRM] Supabase verification failed:',
      error?.message || 'No authenticated session returned'
    );

    return NextResponse.redirect(
      `${SITE_URL}/admin/login?error=${encodeURIComponent(
        error?.message ||
          'Authentication link is invalid or has expired.'
      )}`
    );
  }

  /*
   * ============================================================
   * SUCCESS
   * ============================================================
   *
   * At this point:
   *
   * - token has been verified
   * - Supabase returned a valid session
   * - session cookies have been attached to `response`
   */

  console.log(
    '[AUTH CONFIRM] Authentication successful:',
    data.user?.email || 'unknown user'
  );

  return response;
}